package com.github.cc11001100.weavergirl.api.matcher;

import com.github.cc11001100.weavergirl.api.ValidationUtils;
import java.util.regex.Pattern;

/**
 * Matcher for selecting target methods to intercept within a matched class.
 *
 * <p>Supports matching by exact method name, regex name pattern, annotation, full signature (name +
 * parameter types), constructor, field accessor, or a wildcard that matches any method. Use the
 * static factory methods to create matchers.
 *
 * <h3>MatchType semantics</h3>
 *
 * <ul>
 *   <li>{@link MatchType#EXACT_NAME} &mdash; matches the method name exactly
 *   <li>{@link MatchType#NAME_PATTERN} &mdash; matches the method name against a regex
 *   <li>{@link MatchType#ANNOTATION} &mdash; matches methods annotated with the specified
 *       annotation (resolved by the core engine at class-load time)
 *   <li>{@link MatchType#SIGNATURE} &mdash; matches by method name and parameter types
 *   <li>{@link MatchType#CONSTRUCTOR} &mdash; matches constructors only
 *   <li>{@link MatchType#CFIELD_GET} &mdash; matches ByteBuddy-generated field-get accessors
 *   <li>{@link MatchType#CFIELD_SET} &mdash; matches ByteBuddy-generated field-set accessors
 *   <li>{@link MatchType#ARGS} &mdash; matches methods whose parameter types at given indexes
 *       carry a specific annotation
 *   <li>{@link MatchType#ANY} &mdash; matches all methods
 * </ul>
 *
 * <h3>Usage example</h3>
 *
 * <pre>
 * MethodMatcher exact     = MethodMatcher.byName("process");
 * MethodMatcher pattern   = MethodMatcher.byNamePattern("process.*");
 * MethodMatcher annotated = MethodMatcher.byAnnotation("com.example.Traced");
 * MethodMatcher sig       = MethodMatcher.bySignature("process", "java.lang.String,int");
 * MethodMatcher fieldGet  = MethodMatcher.byFieldGet("value");
 * MethodMatcher fieldSet  = MethodMatcher.byFieldSet("value");
 * MethodMatcher all       = MethodMatcher.any();</pre>
 *
 * @see ClassMatcher
 * @see com.github.cc11001100.weavergirl.api.pointcut.Pointcut
 * @since 1.0.0
 */
public class MethodMatcher {

  /**
   * Determines how a method name or metadata is matched.
   *
   * <p>{@code EXACT_NAME}, {@code NAME_PATTERN}, {@code SIGNATURE}, and {@code ANY} are evaluated
   * by {@link #matches(String)} or {@link #matches(String, Class[])}. {@code ANNOTATION} is
   * resolved by the core engine at bytecode-instrumentation time.
   */
  public enum MatchType {
    /** Match by exact method name. */
    EXACT_NAME,
    /** Match by regex pattern against the method name. */
    NAME_PATTERN,
    /** Match methods bearing a specific annotation. */
    ANNOTATION,
    /** Match by method name and parameter types (signature). */
    SIGNATURE,
    /** Match constructors only. */
    CONSTRUCTOR,
    /** Match methods whose parameter types at given indexes carry a specific annotation. */
    ARGS,
    /** Match all methods. */
    ANY,
    /** Match field-get accessors generated by ByteBuddy for instance/static field reads. */
    CFIELD_GET,
    /** Match field-set accessors generated by ByteBuddy for instance/static field writes. */
    CFIELD_SET
  }

  private final MatchType matchType;
  private final String pattern;
  private final Pattern compiledRegex;
  private final String argumentAnnotationClassName;
  private final int[] argumentIndexes;

  private MethodMatcher(MatchType matchType, String pattern) {
    this(matchType, pattern, null, null);
  }

  private MethodMatcher(
      MatchType matchType,
      String pattern,
      String argumentAnnotationClassName,
      int[] argumentIndexes) {
    this.matchType = matchType;
    this.pattern = pattern;
    this.compiledRegex = (matchType == MatchType.NAME_PATTERN) ? Pattern.compile(pattern) : null;
    this.argumentAnnotationClassName = argumentAnnotationClassName;
    this.argumentIndexes = argumentIndexes;
  }

  /**
   * Creates a matcher that matches a method by its exact name.
   *
   * @param methodName the method name (e.g., {@code "process"})
   * @return a new MethodMatcher with {@link MatchType#EXACT_NAME}
   * @throws IllegalArgumentException if {@code methodName} is null or empty
   */
  public static MethodMatcher byName(String methodName) {
    return new MethodMatcher(
        MatchType.EXACT_NAME, ValidationUtils.requireNonEmpty(methodName, "methodName"));
  }

  /**
   * Creates a matcher that matches a method name against a regular expression.
   *
   * @param regex a Java regex pattern (e.g., {@code "process.*"})
   * @return a new MethodMatcher with {@link MatchType#NAME_PATTERN}
   * @throws IllegalArgumentException if {@code regex} is null or empty
   */
  public static MethodMatcher byNamePattern(String regex) {
    return new MethodMatcher(
        MatchType.NAME_PATTERN, ValidationUtils.requireNonEmpty(regex, "regex"));
  }

  /**
   * Creates a matcher that matches methods annotated with the specified annotation.
   *
   * <p>Annotation matching is resolved by the core engine at class-load time; it is not evaluated
   * by {@link #matches(String)}.
   *
   * @param annotationClassName the fully-qualified annotation class name (e.g., {@code
   *     "com.example.Traced"})
   * @return a new MethodMatcher with {@link MatchType#ANNOTATION}
   * @throws IllegalArgumentException if {@code annotationClassName} is null or empty
   */
  public static MethodMatcher byAnnotation(String annotationClassName) {
    return new MethodMatcher(
        MatchType.ANNOTATION,
        ValidationUtils.requireNonEmpty(annotationClassName, "annotationClassName"));
  }

  /**
   * Creates a matcher that matches methods by name and parameter types (signature).
   *
   * <p>Parameter types are specified as a comma-separated string of fully-qualified class names.
   * For example, {@code bySignature("process", "java.lang.String,int")} matches a method named
   * {@code process} that takes a {@code String} and an {@code int}.
   *
   * @param methodName the method name
   * @param parameterTypes comma-separated fully-qualified parameter type names (e.g., {@code
   *     "java.lang.String,int"})
   * @return a new MethodMatcher with {@link MatchType#SIGNATURE}
   * @throws IllegalArgumentException if {@code methodName} is null or empty, or if {@code
   *     parameterTypes} is null
   */
  public static MethodMatcher bySignature(String methodName, String parameterTypes) {
    ValidationUtils.requireNonEmpty(methodName, "methodName");
    ValidationUtils.requireNonNull(parameterTypes, "parameterTypes");
    return new MethodMatcher(MatchType.SIGNATURE, methodName + "(" + parameterTypes + ")");
  }

  /**
   * Creates a matcher that matches any method.
   *
   * @return a new MethodMatcher with {@link MatchType#ANY}
   */
  public static MethodMatcher any() {
    return new MethodMatcher(MatchType.ANY, "*");
  }

  /**
   * Creates a matcher that matches constructors only.
   *
   * <p>At runtime, {@link #matches(String)} returns {@code true} only for {@code "<init>"}. The
   * core engine additionally applies ByteBuddy's {@code isConstructor()} matcher at transformation
   * time.
   *
   * @return a new MethodMatcher with {@link MatchType#CONSTRUCTOR}
   * @since 1.5.0
   */
  public static MethodMatcher byConstructor() {
    return new MethodMatcher(MatchType.CONSTRUCTOR, "<init>");
  }

  /**
   * Creates a matcher that matches constructors with specific parameter types.
   *
   * <p>Parameter types are specified as a comma-separated string of fully-qualified class names,
   * matching the convention of {@link #bySignature(String, String)}.
   *
   * @param parameterTypes comma-separated fully-qualified parameter type names (e.g., {@code
   *     "java.lang.String,int"}); empty for no-arg constructor
   * @return a new MethodMatcher with {@link MatchType#CONSTRUCTOR}
   * @since 1.5.0
   */
  public static MethodMatcher byConstructor(String parameterTypes) {
    ValidationUtils.requireNonNull(parameterTypes, "parameterTypes");
    return new MethodMatcher(MatchType.CONSTRUCTOR, "<init>(" + parameterTypes + ")");
  }

  /**
   * Creates a matcher for ByteBuddy-generated field-get accessors. These synthetic accessor
   * methods are generated when advice reads an instance or static field via {@code @FieldValue}.
   *
   * @param fieldName the field name to match
   * @return a new MethodMatcher with {@link MatchType#CFIELD_GET}
   * @since 2.0.0
   */
  public static MethodMatcher byFieldGet(String fieldName) {
    return new MethodMatcher(
        MatchType.CFIELD_GET, ValidationUtils.requireNonEmpty(fieldName, "fieldName"));
  }

  /**
   * Creates a matcher for ByteBuddy-generated field-set accessors. These synthetic accessor
   * methods are generated when advice writes an instance or static field via {@code @FieldValue}.
   *
   * @param fieldName the field name to match
   * @return a new MethodMatcher with {@link MatchType#CFIELD_SET}
   * @since 2.0.0
   */
  public static MethodMatcher byFieldSet(String fieldName) {
    return new MethodMatcher(
        MatchType.CFIELD_SET, ValidationUtils.requireNonEmpty(fieldName, "fieldName"));
  }

  /**
   * Creates a matcher that matches methods whose parameter types at given indexes carry the
   * specified annotation.
   *
   * <p>This corresponds to the {@code @args} pointcut designator. Indexes are zero-based.
   *
   * @param annotationClassName the fully-qualified annotation class name present on parameter types
   * @param argumentIndexes zero-based argument indexes to match
   * @return a new MethodMatcher with {@link MatchType#ARGS}
   * @since 1.9.0
   */
  public static MethodMatcher byArgumentAnnotation(String annotationClassName, int... argumentIndexes) {
    ValidationUtils.requireNonEmpty(annotationClassName, "annotationClassName");
    if (argumentIndexes == null || argumentIndexes.length == 0) {
      throw new IllegalArgumentException(
          "argumentIndexes must contain at least one index for @args matching");
    }
    return new MethodMatcher(
        MatchType.ARGS,
        annotationClassName,
        annotationClassName,
        argumentIndexes);
  }

  /**
   * Returns the match type of this matcher.
   *
   * @return the match type
   */
  public MatchType getMatchType() {
    return matchType;
  }

  /**
   * Returns the pattern string used for matching.
   *
   * <p>For {@link MatchType#SIGNATURE}, the pattern is in the form {@code
   * methodName(param1,param2)}.
   *
   * @return the pattern string
   */
  public String getPattern() {
    return pattern;
  }

  /**
   * Returns the argument annotation class name for {@link MatchType#ARGS} matchers.
   *
   * @return the annotation class name, or null
   * @since 1.9.0
   */
  public String getArgumentAnnotationClassName() {
    return argumentAnnotationClassName;
  }

  /**
   * Returns the argument indexes for {@link MatchType#ARGS} matchers.
   *
   * @return the argument indexes, or null
   * @since 1.9.0
   */
  public int[] getArgumentIndexes() {
    return argumentIndexes;
  }

  /**
   * Tests whether the given method name matches this matcher.
   *
   * <p>This method supports {@link MatchType#EXACT_NAME}, {@link MatchType#NAME_PATTERN}, {@link
   * MatchType#SIGNATURE} (name part only), and {@link MatchType#ANY}. For {@link
   * MatchType#ANNOTATION}, this method always returns {@code false}.
   *
   * <p>For {@code SIGNATURE} matchers, only the method name portion of the signature is compared.
   * Use {@link #matches(String, Class[])} for full signature matching.
   *
   * @param methodName the method name to test
   * @return true if the method name matches
   */
  public boolean matches(String methodName) {
    switch (matchType) {
      case EXACT_NAME:
        return pattern.equals(methodName);
      case NAME_PATTERN:
        return compiledRegex != null && compiledRegex.matcher(methodName).matches();
      case ANY:
        return true;
      case CONSTRUCTOR:
        return "<init>".equals(methodName);
      case SIGNATURE:
        int parenIdx = pattern.indexOf('(');
        if (parenIdx < 0) return false;
        String patternName = pattern.substring(0, parenIdx);
        return patternName.equals(methodName);
      case ANNOTATION:
        // Annotation matching is resolved by the core engine (ByteBuddy)
        // at bytecode-instrumentation time. If this method is being called,
        // the method has already been selected by ByteBuddy's annotation matcher.
        return true;
      case CFIELD_GET:
      case CFIELD_SET: {
        String base = pattern;
        if (base == null || base.isEmpty()) {
          return false;
        }
        if (methodName == null || methodName.isEmpty()) {
          return false;
        }
        if (methodName.equals(base)) {
          return true;
        }
        if (matchType == MatchType.CFIELD_GET) {
          if (("get" + base).equals(methodName) || ("access$" + base).equals(methodName)) {
            return true;
          }
        } else {
          if (("set" + base).equals(methodName) || ("access$set" + base).equals(methodName)) {
            return true;
          }
        }
        return false;
      }
      default:
        return false;
    }
  }

  /**
   * Tests whether the given method name and parameter types match this matcher.
   *
   * <p>For {@link MatchType#SIGNATURE}, both the method name and parameter types are checked.
   * Parameter types are compared by their fully-qualified names against the types encoded in the
   * signature pattern.
   *
   * <p>For all other match types, this delegates to {@link #matches(String)}.
   *
   * @param methodName the method name to test
   * @param parameterTypes the parameter types of the method, or null for no parameters
   * @return true if the method signature matches
   */
  public boolean matches(String methodName, Class<?>[] parameterTypes) {
    if (matchType == MatchType.SIGNATURE || matchType == MatchType.CONSTRUCTOR) {
      // Parse "methodName(param1,param2)" from pattern
      // For CONSTRUCTOR, pattern is "<init>" or "<init>(param1,param2)"
      int parenIdx = pattern.indexOf('(');
      if (parenIdx < 0) {
        // No parenthesized params: match the name only (any parameter signature)
        // This handles byConstructor() which matches ALL constructors.
        return pattern.equals(methodName);
      }
      String patternName = pattern.substring(0, parenIdx);
      if (!patternName.equals(methodName)) return false;
      String patternParams = pattern.substring(parenIdx + 1, pattern.length() - 1);
      if (patternParams.isEmpty()) {
        return parameterTypes == null || parameterTypes.length == 0;
      }
      String[] expectedTypes = patternParams.split(",");
      if (parameterTypes == null || parameterTypes.length != expectedTypes.length) return false;
      for (int i = 0; i < expectedTypes.length; i++) {
        if (!expectedTypes[i].trim().equals(parameterTypes[i].getName())) return false;
      }
      return true;
    }

    if (matchType == MatchType.ARGS) {
      return matchesArgumentAnnotation(parameterTypes);
    }

    return matches(methodName);
  }

  private boolean matchesArgumentAnnotation(Class<?>[] parameterTypes) {
    if (argumentAnnotationClassName == null
        || argumentIndexes == null
        || argumentIndexes.length == 0) {
      return false;
    }
    if (parameterTypes == null || parameterTypes.length == 0) {
      return false;
    }
    try {
      Class<? extends java.lang.annotation.Annotation> annotationClass =
          (Class<? extends java.lang.annotation.Annotation>)
              Class.forName(argumentAnnotationClassName);
      String targetSimpleName = annotationClass.getSimpleName();
      for (int index : argumentIndexes) {
        if (index < 0 || index >= parameterTypes.length) {
          return false;
        }
        Class<?> paramType = parameterTypes[index];
        // Match if the parameter type carries the annotation, or if the
        // parameter type class itself IS the annotation class (test model).
        boolean matches = paramType.isAnnotationPresent(annotationClass)
            || paramType.equals(annotationClass)
            || paramType.getSimpleName().equals(targetSimpleName);
        if (!matches) {
          return false;
        }
      }
      return true;
    } catch (Throwable e) {
      return false;
    }
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (!(o instanceof MethodMatcher)) return false;
    MethodMatcher that = (MethodMatcher) o;
    return pattern.equals(that.pattern) && matchType == that.matchType;
  }

  @Override
  public int hashCode() {
    return pattern.hashCode() * 31 + matchType.hashCode();
  }

  @Override
  public String toString() {
    return "MethodMatcher{" + matchType + ": " + pattern + "}";
  }
}
