apiVersion: v1
kind: Service
metadata:
  name: {{ include "weaver-girl.fullname" . }}
  labels:
    {{- include "weaver-girl.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
    - name: health
      port: {{ .Values.service.healthPort }}
      targetPort: health
      protocol: TCP
  selector:
    app: {{ .Values.targetApplication.name | default "application" }}
